name: 使用问题
description: 询问工具用法。
title: "[使用问题]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: 问题
      description: 你想了解什么？
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 背景
      description: 你已经试过哪些步骤？
    validations:
      required: false
